api_platform:
    swagger:
        api_keys:
            JWT:
            name: Authorization
            type: header
    title : "Mon blog API"
    description : "Api"
    defaults:
        pagination_items_per_page: 5
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        jsonapi:  ['application/vnd.api+json']
        html:     ['text/html']
        csv:      ['text/csv']


        