api_platform:
    title: 'API BLOG'
    description: 'UNE API POUR MON BLOG'
    formats:
        jsonld:
            mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']
        